kind: pipeline
name: test-pipeline-goapp

steps:

- name: build
  image: golang:1.7
  commands: 
    - go get github.com/SimonWaldherr/micromarkdownGo
    - go get github.com/mxk/go-sqlite/sqlite3
    - go build -o wikiapp
    - ls wikiapp
  when:
    branch:
      - master
    event:
      - push

- name: docker  
  image: plugins/docker
  settings:
    repo: sanjaymv/wikiapp
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    auto_tag: true

